package org.acme.resource;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.Matchers.notNullValue;

import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.security.TestSecurity;
import io.restassured.http.ContentType;
import org.junit.jupiter.api.Test;

/**
 * Integration tests for {@link SurveyResource}. Boots the app via {@code @QuarkusTest}
 * (Dev Services provides PostgreSQL) and authenticates via {@code @TestSecurity}.
 * All endpoints live under the configured {@code quarkus.rest.path=/api/v1}.
 */
@QuarkusTest
class SurveyResourceTest {

    private static final String BASE = "/api/v1/surveys";

    @Test
    void list_requiresAuthentication() {
        given()
            .when().get(BASE)
            .then().statusCode(401);
    }

    @Test
    @TestSecurity(user = "owner-1")
    void create_returns201WithEnvelope() {
        given()
            .contentType(ContentType.JSON)
            .body("{\"title\":\"Customer Feedback\",\"description\":\"Q3\"}")
            .when().post(BASE)
            .then()
            .statusCode(201)
            .body("success", is(true))
            .body("data.id", notNullValue())
            .body("data.title", is("Customer Feedback"))
            .body("data.status", is("draft"))
            .body("data.ownerId", is("owner-1"));
    }

    @Test
    @TestSecurity(user = "owner-1")
    void create_validatesTitle() {
        given()
            .contentType(ContentType.JSON)
            .body("{\"title\":\"\"}")
            .when().post(BASE)
            .then().statusCode(422);
    }

    @Test
    @TestSecurity(user = "owner-1")
    void fullLifecycle_createUpdateGetDelete() {
        // create
        String id = given()
            .contentType(ContentType.JSON)
            .body("{\"title\":\"Lifecycle\"}")
            .when().post(BASE)
            .then().statusCode(201)
            .extract().path("data.id");

        // update with a multiple-choice question
        given()
            .contentType(ContentType.JSON)
            .body("""
                {
                  "title": "Lifecycle v2",
                  "status": "published",
                  "questions": [
                    {
                      "type": "multiple-choice",
                      "title": "Pick one",
                      "required": true,
                      "order": 0,
                      "options": [ {"label": "A"}, {"label": "B"} ]
                    }
                  ]
                }
                """)
            .when().put(BASE + "/" + id)
            .then()
            .statusCode(200)
            .body("data.title", is("Lifecycle v2"))
            .body("data.status", is("published"))
            .body("data.questions.size()", is(1))
            .body("data.questions[0].type", is("multiple-choice"))
            .body("data.questions[0].options.size()", is(2));

        // get
        given()
            .when().get(BASE + "/" + id)
            .then().statusCode(200).body("data.title", is("Lifecycle v2"));

        // delete
        given()
            .when().delete(BASE + "/" + id)
            .then().statusCode(200).body("success", is(true));

        // gone
        given()
            .when().get(BASE + "/" + id)
            .then().statusCode(404).body("success", is(false));
    }

    @Test
    @TestSecurity(user = "owner-1")
    void update_withRatingQuestion_succeeds() {
        String id = given()
            .contentType(ContentType.JSON)
            .body("{\"title\":\"Rating survey\"}")
            .when().post(BASE)
            .then().statusCode(201)
            .extract().path("data.id");

        given()
            .contentType(ContentType.JSON)
            .body("""
                {
                  "title": "Rating survey",
                  "status": "draft",
                  "questions": [
                    {
                      "type": "rating",
                      "title": "How likely to recommend?",
                      "required": false,
                      "order": 0,
                      "settings": { "variant": "nps" }
                    }
                  ]
                }
                """)
            .when().put(BASE + "/" + id)
            .then().statusCode(200)
            .body("data.questions[0].type", is("rating"));
    }

    @Test
    @TestSecurity(user = "owner-1")
    void update_withExistingIds_succeeds() {
        // 1. Create survey
        String surveyId = given()
            .contentType(ContentType.JSON)
            .body("{\"title\":\"Survey with IDs\"}")
            .when().post(BASE)
            .then().statusCode(201)
            .extract().path("data.id");

        // 2. Put a question (IDs will be generated by backend)
        var responseDto = given()
            .contentType(ContentType.JSON)
            .body("""
                {
                  "title": "Survey with IDs v2",
                  "status": "published",
                  "questions": [
                    {
                      "type": "multiple-choice",
                      "title": "Pick one",
                      "required": true,
                      "order": 0,
                      "options": [ {"label": "A"}, {"label": "B"} ]
                    }
                  ]
                }
                """)
            .when().put(BASE + "/" + surveyId)
            .then().statusCode(200)
            .extract().jsonPath();

        String questionId = responseDto.getString("data.questions[0].id");
        String optionAId = responseDto.getString("data.questions[0].options[0].id");
        String optionBId = responseDto.getString("data.questions[0].options[1].id");

        // 3. Put again with the generated IDs (modifying a title)
        given()
            .contentType(ContentType.JSON)
            .body(String.format("""
                {
                  "title": "Survey with IDs v3",
                  "status": "published",
                  "questions": [
                    {
                      "id": "%s",
                      "type": "multiple-choice",
                      "title": "Pick one (modified)",
                      "required": true,
                      "order": 0,
                      "options": [
                        {"id": "%s", "label": "A"},
                        {"id": "%s", "label": "B"}
                      ]
                    }
                  ]
                }
                """, questionId, optionAId, optionBId))
            .when().put(BASE + "/" + surveyId)
            .then().statusCode(200);
    }

    @Test
    @TestSecurity(user = "owner-1")
    void get_unknownIdReturns404() {
        given()
            .when().get(BASE + "/does-not-exist")
            .then().statusCode(404).body("success", is(false));
    }
}

